server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 9769
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: create, update, validate, none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: HOTEL_SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
